functional: #Правильно ли все работает с точки зрения функционала приложения/сайта
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины

non-functional: #Проверка удобства, скорости и безопасности использования приложения/сайта
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен иметь мобильную версию 
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров

implicit: #Требования к приложению, которые не обозначены в задачах, но упрощают и ускоряют процесс использования приложения/сайта
  - При переключении языка сайта, должна меняться цена продукта на валюту страны
  - При переключений страниц каталога, должен отображаться порядковый номер страницы
  - Кнопка «Х» должна выполнять ту же функцию, что и кнопка «Закрыть»
  - При разворачивании кнопки изменения языка, рядом с «English» должен появляться британский флаг
  - Нелогичная кнопка «в наличии», так как покупателю неактуально смотреть товары, которые он не сможет купить. Более того, все товары в наличии
  - Фильтр по категории логичнее сделать с несколькими вариантами ответа, когда фильтр по бренду лучше сделать выпадающим списком
  - Нет возможности отменить фильтр по категории, чтобы вернуться к полному ассортименту
  - Нет формы регистрации, чтобы окончательно заказать товар
  - Нет страницы, где можно просмотреть свои активные заказы
  
